singleuser:
  cpu:
    limit: 1
    guarantee: 0.5
  memory:
    limit: 2G
    guarantee: 1G
  defaultUrl: "/lab"
  serviceAccountName: spark
  image:
    name: singleuser
    tag: v2
    pullPolicy: IfNotPresent
    pullSecrets: []